### ISSUE TITLE
Pandoc on Ubuntu LTS 22.04 is too old

### ISSUE THREAD

**Issue by IdanDor** [max-heller/mdbook-pandoc#35]
First, this seems wonderful and exactly a thing I was looking for, randomly found on reddit.

After attempting to install on my linux mint (21.1, based on ubuntu 22.04) I got the following error:
```text
2023-12-24 12:04:21 [INFO] (mdbook::renderer): Invoking the "pandoc" renderer
Unknown extension: attributes
pandoc exited unsuccessfully
```

After a bit of digging I found [this](https://github.com/jgm/pandoc/commit/8d523d80d4120413f6b62bf833d6da8f2a69b925) commit which is from june 2020 which adds the `attributes` extension, while the pandoc version on ubuntu is [2.9.2.1-3ubuntu2](https://launchpad.net/ubuntu/+source/pandoc) which is based on [2020-03-23](https://pandoc.org/releases.html#pandoc-2.9.2.1-2020-03-23).

I'm not sure if attempting to support older pandoc versions is feasible, I can likely get myself a more updated version, but if it isn't, perhaps add that to the readme/installation section?

**Comment by max-heller** [comment]
Thanks for the issue, I'd seen that Ubuntu ships very old versions of Pandoc but hadn't tested with them, so it's not surprising things break.

It should be possible to support older versions of Pandoc, but it will likely result in lower-quality output. I'll see what I can do and add a note to the README mentioning the oldest version with full functionality.

**Comment by max-heller** [comment]
I pushed a WIP solution to #37 if you want to try it out
