### ISSUE TITLE
About outputting PDF with Chinese information

### ISSUE THREAD

**Issue by oldbotman** [max-heller/mdbook-pandoc#47]
I want to use this to output a PDF in Chinese. Is this the correct setting?
`
pdf-engine = "xelatex"
`
`
[output.pandoc.profile.pdf.variables]
`
`
CJKmainfont = "SimSun"
`

**Comment by oldbotman** [comment]
yep，i just try and it was work

**Comment by Guaderxx** [comment]
This is useful to me too, Thank you.
